# Generated by Django 3.0.2 on 2020-01-07 22:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('final_data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
            options={
                'unique_together': {('league_id', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('abbrev', models.CharField(max_length=4)),
                ('division', models.IntegerField()),
                ('league_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='league_history.LeagueYear')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='league_history.Owner')),
            ],
            options={
                'unique_together': {('team_id', 'league_year')},
            },
        ),
    ]
