# Generated by Django 3.0.2 on 2020-01-08 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_history', '0001_owners_leagues_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('home_score', models.FloatField(null=True)),
                ('away_score', models.FloatField(null=True)),
                ('playoff_tier', models.CharField(max_length=64, null=True)),
                ('away_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='league_history.Team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='league_history.Team')),
                ('league_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchups', to='league_history.LeagueYear')),
            ],
            options={
                'unique_together': {('league_year', 'week', 'home_team', 'away_team')},
            },
        ),
    ]
