# Generated by Django 3.0.2 on 2020-01-10 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_history', '0003_pro_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('jersey', models.SmallIntegerField(null=True)),
                ('position', models.CharField(choices=[('QB', 'QB'), ('RB', 'RB'), ('WR', 'WR'), ('TE', 'TE'), ('D/ST', 'D/ST'), ('K', 'K')], max_length=8)),
                ('pro_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='league_history.ProTeam')),
            ],
        ),
    ]
