# Generated by Django 3.0.2 on 2020-01-10 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_history', '0004_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_num', models.IntegerField()),
                ('round_pick', models.IntegerField()),
                ('is_keeper', models.BooleanField()),
                ('league_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to='league_history.LeagueYear')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to='league_history.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to='league_history.Team')),
            ],
        ),
    ]
