# Generated by Django 3.0.2 on 2020-01-13 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_history', '0005_draftpicks'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField()),
                ('lineup_position', models.PositiveSmallIntegerField(null=True)),
                ('points', models.FloatField(default=0.0)),
                ('proj_points', models.FloatField(default=0.0)),
                ('league_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_scores', to='league_history.LeagueYear')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_scores', to='league_history.Player')),
                ('pro_opponent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='box_scores_opp', to='league_history.ProTeam')),
                ('pro_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_score', to='league_history.ProTeam')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box_scores', to='league_history.Team')),
            ],
        ),
    ]
